/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      white: "#ffffff",
      black: "#000000",
      primary: "#cda715",
      secondary: "#b6eada",
      content: "#efedff",
      space: {
        1: "#03001c",
        2: "#303047",
        3: "#301e67",
        4: "#5b8fb9",
      },
    },
    fontFamily: {
      ssp: ["Source Sans Pro", "sans-serif"],
      audiowide: ["Audiowide", "cursive"],
    },
    extend: {},
  },
  plugins: [],
  corePlugins: [
    "accessibility",
    "alignItems",
    "backgroundColor",
    "borderColor",
    "display",
    "flex",
    "flexBasis",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "fontFamily",
    "fontSize",
    "fontWeight",
    "gap",
    "height",
    "justifyContent",
    "margin",
    "padding",
    "textAlign",
    "textColor",
    "textTransform",
    "width",
  ],
};
